### ISSUE TITLE
test_new.py fails with: TypeError: __init__() got an unexpected keyword argument 'username'

### ISSUE THREAD

**Issue by stbuerger** [sander1988/pyIndego#118]
Just trying the latest development branch version for/with the new Bosch Single-ID authentication and failing with the following error :

```
Traceback (most recent call last):
  File "_MY_PATH_/test_new.py", line 132, in <module>
    main(config)
  File "_MY_PATH_/test_new.py", line 20, in main
    with IndegoClient(**config) as indego:
TypeError: __init__() got an unexpected keyword argument 'username'
```

with config.json like:

```
{
  "username": "my_email@xyz.de",
  "password": "my_secret_pw",
  "serial": "123456"
}

```

**Comment by jm-73** [comment]
I am not using the text_new. Please make a PR when you find the error! 
The HA Integration works.
